export type Company = Record<string, unknown>;

export const SECTOR_MAP: Record<string, string> = {
  "Acero": "Steel",
  "AFP": "Pension Funds",
  "Alimentos": "Food & Beverages",
  "Bancos": "Banks",
  "Bebidas": "Beverages",
  "Conglomerados": "Conglomerates",
  "Construcción": "Construction",
  "Dep y Ent": "Entertainment",
  "Electrico": "Utilities – Electric",
  "Empaque": "Packaging",
  "Explosivos": "Explosives & Mining Chem",
  "Forestal": "Forestry & Pulp",
  "Gas y Petroleo": "Oil & Gas",
  "Grup. Financ.": "Financial Groups",
  "Inversiones": "Investments",
  "Manufactura": "Manufacturing",
  "Min. Metal": "Mining – Metals",
  "Min. No-Metal": "Mining – Non-Metals",
  "Real Estate": "Real Estate",
  "Retail": "Retail",
  "Salmones y Pesca": "Salmon & Fishing",
  "Seguros y Salud": "Insurance & Healthcare",
  "Serv. Públicos": "Public Utilities",
  "Tecnología": "Technology",
  "Telecom": "Telecom",
  "Transp y puerto": "Transport & Ports",
  "Vinos": "Wines",
};
